### ISSUE TITLE
listObjects Exception 

### ISSUE THREAD

**Issue by micsanbr** [diagnosia/flutter_aws_s3_client#1]
Hi, this looks quite promising.
I'm using it to download files from a storage bucket for now.

for the configuration I used:
bucket: "$awsBucket.s3.$awsRegion.amazonaws.com"
(notice the .s3)

s3client.getObject // works :)
s3client.buildSignedGetParams // works :)

ListBucketResult listBucketResult = await s3client.listObjects(prefix: "/", delimiter: "/");

Exception has occurred.
DeserializationError (Deserializing '[Error, {Code: AccessDenied, Message: Access Denied, RequestId: 6AF7623EE000E...' to 'ListBucketResultParker' failed due to: Tried to build class "ListBucketResultParker" but nested builder for field "result" threw: Tried to construct class "ListBucketResult" with null field "name". This is forbidden; to allow it, mark "name" with @nullable.)

**Comment by knaeckeKami** [comment]
Hi,
There seems to be 2 problems:

1. You don't have the permission to list objects in this bucket. Make sure the IAM user has the following rights: 

-  ListBucket
-  ListBucketVersions (I think, might work without that)

2. This library doesn't handle permisson errors at all at the moment :) I'll try to reproduce this error and release a new version that returns a better error description.

**Comment by micsanbr** [comment]
You are so right, I think that must be it.

**Comment by knaeckeKami** [comment]
Version 0.2.0 throws an exception with a description what happened in such cases.
Does this fix your problem?

**Comment by micsanbr** [comment]
Nice, thanks. Wonderful plugin btw.
