### ISSUE TITLE
Upload files

### ISSUE THREAD

**Issue by softower** [diagnosia/flutter_aws_s3_client#2]
Does this package provide options to upload a file too? I do not find it in the docs

**Comment by knaeckeKami** [comment]
Currently, it only supports downloading objects and listing objects in a bucket.
I currently don't really have time to add more features. but I will happily merge pull requests.

Uploading seems to be supported by https://pub.dev/packages/flutter_amazon_s3 . Maybe you can look at https://pub.dev/packages/aws_client if this package offers what you need.

**Comment by canyonwan** [comment]
hello! sry, my english may be not good!
i will use this for my company for upload images/pdf files/ and videos, but i don't find this function!

when i used ,find this error .
Exception has occurred.
FormatException (FormatException: Invalid radix-10 number (at character 1)
//121.46.26.133:12001
^
)

bellow is my use
static final AwsS3Client s3client = AwsS3Client(
    region: 'eu-central-1',
    host: "http://121.46.26.133:12001",
    bucketId: 'bucketname-java',
    accessKey: "VYJ0ABSH87EDDW7SCHPI",
    secretKey: "ilJKotHwmdPxy0M0lAz50VifMtSH2buRZ3i5C7CH",
  );
  void printHelp() async {
    final response = await s3client.getObject("yourObjectId");
    print(response.body.toString());
}

**Comment by knaeckeKami** [comment]
Hi!

I would advise you to invalidate your secret key and generate a new one! You should never share you secret key - it's now public and anyone could use it!

As for uploading - I am sorry, but this package only supports downloading at the moment, no uploading. 

There are other packages that support uploading, like https://pub.dev/packages/aws_s3_client , please check them out.

**Comment by zyang96** [comment]
Hi,

I'm having some issue to download data from s3 with this library. I got this error:

`
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>ASIAxxxxxxxx</AWSAccessKeyId><RequestId>BBE2A44887A4A78E</RequestId><HostId>d/KvG83r/rvz6iRV9RraodnkfgbuHtrQM5f82gbGBPGypNP9tbRsaHFHG6ZoIft4BCplQ2JUmcM=</HostId></Error>
`

Do you know what could be wrong? I also tried to use session token when constructing the client. No luck.

**Comment by ayush97123** [comment]
Hey does it support getting the metadata of the files stored in S3? Like getting the last modified date etc.

**Comment by knaeckeKami** [comment]
@ayush97123  yes, use the `listObjects` method. ListBucketResult a field `contents` with that information.

@zyang96 I would say check your AWS credentials, make sure that they are valid. can you do requests with these credentials via other means (e.g. CLI tools)?

**Comment by ayush97123** [comment]
> @ayush97123 yes, use the `listObjects` method. ListBucketResult a field `contents` with that information.

Hey, I tried this but it returns all the files that are present in that bucket then I have to iterate through them and then get the lastModifiedDate. Is there any better approach to get lastModifiedDate?  Also I am having trouble extracting data from the contents field. Can you also suggest a good way to extract that data?

**Comment by knaeckeKami** [comment]
I don't think S3 offers a way to get objects by lastModifiedDate, so I don't think there's a better way.
What do you mean by extracting data from the contents field? Where are you struggling exactly?

**Comment by knaeckeKami** [comment]
Hey,

Since there is now an official package for accessing AWS services, I decided to not longer support this package. please migrate to https://github.com/aws-amplify/amplify-flutter / https://pub.dev/packages/amplify_storage_s3/example
