### ISSUE TITLE
Is this supported for flutter web?

### ISSUE THREAD

**Issue by UttamPanchasara** [diagnosia/flutter_aws_s3_client#5]
Would like to use this to download the file in flutter web.

**Comment by knaeckeKami** [comment]
I never tested it. I wrote this library when flutter web was pre-alpha so this was not in my mind at that time.

But I think it should work. I'll try it later and get back to you.

**Comment by knaeckeKami** [comment]
I just tried it, yes it works fine on the web. Just make sure you set the CORS configuration correctly otherwise the browser blocks the requests.

**Comment by UttamPanchasara** [comment]
Hey thanks for your time, Yes the configuration was passed correctly. but it was not working with me, will try again, and it would be great if you can add an example for flutter web.

**Comment by knaeckeKami** [comment]
It should work the same way on web as on mobile or desktop.
Can you show me the error/exception that you get?
