### ISSUE TITLE
Problem with Signature V2 on requests

### ISSUE THREAD

**Issue by nekoto-kun** [diagnosia/flutter_aws_s3_client#7]
Hi, I just tried out the package, but it seems my case doesn't quite supported yet. I found that your request builder is using Signature V4 for signing requests. My target host are using Signature V2 and probably it makes my responses always returning 403. Maybe you can add this one feature to allow choosing signature version when initializing the client.

One more question, is it a mandatory to put all keys on client initialization, but I just want to retrieve list of objects from my public bucket? Thanks.

**Comment by knaeckeKami** [comment]
Hi!

Are you sure that your bucket does not support v4 signing?
I did some research and it seems like v2 has been deprecated for a few years now and v4 is supported everywhere. (https://aws.amazon.com/blogs/aws/amazon-s3-update-sigv2-deprecation-period-extended-modified/ ).

I don't know how AWS handles access to public buckets. Do you have an IAM user? If you do, I think it should work.

**Comment by nekoto-kun** [comment]
sorry, I didn't search through the official blog and just know that it has been deprecated, thanks for the info 👍🏻. However, my storage host do still require V2 signature (based on their knowledge base if users want to browse the bucket using S3 browser). I need to tell my team to do more research about our host on this matter.

Anyway, the objectives of the package generally match with my requirements for additional feature for my app —I just want to make our S3 browsable and users can directly download files to their phone. Beforehand, I used some workaround to just call full path of the bucket, and that's totally inefficient and I got overwhelmed about how to iterate the thousands of keys efficiently, from XML which I can't get along with well... so I came to your package and my hope is almost achieved 😅

Thanks for your response.

**Comment by knaeckeKami** [comment]
Hey,

Since there is now an official package for accessing AWS services, I decided to not longer support this package. please migrate to https://github.com/aws-amplify/amplify-flutter / https://pub.dev/packages/amplify_storage_s3/example
