### ISSUE TITLE
Exception: Xml2JsonException: message = parse error - invalid XML

### ISSUE THREAD

**Issue by suriyaKalidoss21** [diagnosia/flutter_aws_s3_client#8]
When I tried to access the file in the bucket I got the JSON exception using below code in a latest package, is there is a solution for this, I also attached my bucket image, Please provide a solution for this issue

**My Code**:
`const region = "ap-south-1";
  const bucketId = "bucketname/videos";
  final AwsS3Client s3client = AwsS3Client(
      region: region,
      host: "s3.ap-south-1.amazonaws.com",
      bucketId: bucketId,
      accessKey: "xxxxxxxx",
      secretKey: "xxxxxxxxxxxxxxxxxxxx");

  final listBucketResult =
      await s3client.listObjects(delimiter: 'demo/test', prefix: '/');
  print(listBucketResult.toString());

  final response = await s3client
      .getObject("ba90098ad645d2f70569e3bf9332db53_69.m3u8");
  print(response.body.toString());`
 

Stack Trace:
`
E/flutter (16862): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Xml2JsonException: message = parse error - invalid XML
E/flutter (16862): #0      Xml2Json.parse 
package:xml2json/src/xml2json.dart:56
E/flutter (16862): #1      _parseListObjectResponse 
package:flutter_aws_s3_client/…/client/client.dart:144
E/flutter (16862): #2      AwsS3Client.listObjects 
package:flutter_aws_s3_client/…/client/client.dart:57
E/flutter (16862): <asynchronous suspension>
E/flutter (16862): #3      main 
package:s3fileget/main.dart:14
E/flutter (16862): #4      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:241:25)
E/flutter (16862): #5      _rootRun  (dart:async/zone.dart:1184:13)
E/flutter (16862): #6      _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter (16862): #7      _runZoned  (dart:async/zone.dart:1619:10)`

Bucket directory image: ![Screenshot_3](https://user-images.githubusercontent.com/51110790/88641214-80c50700-d0dc-11ea-9ab9-7eeb9a06c0cb.png)

**Comment by knaeckeKami** [comment]
Hi, I think you swapped "delimiter" and "prefix". Could you try with 

```dart
await s3client.listObjects(prefix: 'demo/test', delimiter: '/');
```

**Comment by suriyaKalidoss21** [comment]
final listBucketResult =
      await s3client.listObjects(prefix: 'demo/test', delimiter: '/');
`/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Xml2JsonException: message = parse error - invalid XML
E/flutter (30771): #0      Xml2Json.parse 
package:xml2json/src/xml2json.dart:56
E/flutter (30771): #1      _parseListObjectResponse 
package:flutter_aws_s3_client/…/client/client.dart:144
E/flutter (30771): #2      AwsS3Client.listObjects 
package:flutter_aws_s3_client/…/client/client.dart:57
E/flutter (30771): <asynchronous suspension>
E/flutter (30771): #3      main 
package:s3fileget/main.dart:14
E/flutter (30771): #4      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:241:25)
E/flutter (30771): #5      _rootRun  (dart:async/zone.dart:1184:13)
E/flutter (30771): #6      _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter (30771): #7      _runZoned  (dart:async/zone.dart:1619:10)
`
Tried above but still, the issue occurs

**Comment by knaeckeKami** [comment]
Ah sorry, I think it should be 
```dart
await s3client.listObjects(prefix: 'demo/test/', delimiter: '/');
```
(note the trailing '/' on the prefix)

If that does not help, could you set a breakpoint on line 56 of `client.dart`(in the method (`listObjects`) of this library, and check the contents of 
`response.body` during a request?

Debugging these issues can be hard, as it's not possible for me to reproduce the exact state of the bucket, so I need you to help me out a bit ;)

**Comment by suriyaKalidoss21** [comment]
I tried this await s3client.listObjects(prefix: 'demo/test/', delimiter: '/'); but issue stilloccurs,


 I can't able to debug the app using your plugin GitHub sample,
these issues occur there 
![image](https://user-images.githubusercontent.com/51110790/88658617-56ca0f80-d0f1-11ea-9483-d4b412dd902f.png)

**Comment by knaeckeKami** [comment]
Ah, yes it seems the example is broken, it should work just via dart though, it does not actually use flutter.
I will fix it sometime.

You should be able to see the network traffic by using this class:

```dart

import 'dart:convert';
import 'package:http/http.dart';

class DebugClient extends BaseClient {
  final Client _client;

  DebugClient([Client client]) : _client = client ?? Client();

  @override
  void close() {
    _client.close();
  }

  @override
  Future<StreamedResponse> send(BaseRequest request) {
    return _client.send(request).then((response) async {
      final responseString = await response.stream.bytesToString();
      print(response.statusCode);
      for (final h in response.headers.entries) {
        print(h.key + ":" + h.value);
      }
      print(responseString);
      return StreamedResponse(ByteStream.fromBytes(utf8.encode(responseString)),
          response.statusCode,
          headers: response.headers,
          reasonPhrase: response.reasonPhrase,
          persistentConnection: response.persistentConnection,
          contentLength: response.contentLength,
          isRedirect: response.isRedirect,
          request: response.request);
    });
  }
}
```
And constructing the client like that:

```dart

final AwsS3Client s3client = AwsS3Client(
region: region,
host: "s3.ap-south-1.amazonaws.com",
bucketId: bucketId,
client: DebugClient(Client()),
accessKey: "xxxxxxxx",
secretKey: "xxxxxxxxxxxxxxxxxxxx");

```

This should now print the response headers and body if you do requests. 

If I can see what the response of S3 actually is, I should be able to fix this error.

**Comment by suriyaKalidoss21** [comment]
Response in console:
`I/flutter (13581): date:Tue, 28 Jul 2020 12:56:36 GMT
I/flutter (13581): accept-ranges:bytes
I/flutter (13581): content-length:0
I/flutter (13581): etag:"d41d8cd98f00b204e9800998ecf8427e"
I/flutter (13581): x-amz-request-id:6AAB4A4BF1C09081
I/flutter (13581): content-type:application/x-directory
I/flutter (13581): x-amz-id-2:C4OKMWCKJ2erU4B99dKqI81Usu0v3Zvl402jA2HHfKxWMNpRu3M3ugNBg/oWVSIA+aq44vxAph8=
I/flutter (13581): server:AmazonS3
I/flutter (13581):
E/flutter (13581): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Xml2JsonException: message = parse error - invalid XML
E/flutter (13581): #0      Xml2Json.parse 
package:xml2json/src/xml2json.dart:56
E/flutter (13581): #1      _parseListObjectResponse 
package:flutter_aws_s3_client/…/client/client.dart:144
E/flutter (13581): #2      AwsS3Client.listObjects 
package:flutter_aws_s3_client/…/client/client.dart:57
E/flutter (13581): <asynchronous suspension>
E/flutter (13581): #3      main 
package:s3fileget/main.dart:16
E/flutter (13581): #4      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:241:25)
E/flutter (13581): #5      _rootRun  (dart:async/zone.dart:1184:13)
E/flutter (13581): #6      _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter (13581): #7      _runZoned  (dart:async/zone.dart:1619:10)
Launching lib\main.dart on SM A605G in debug mode...
Parameter format not correct -
√ Built build\app\outputs\apk\debug\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:54319/q-Pd2t8tKw0=/ws
I/flutter (13581): 200
I/flutter (13581): last-modified:Tue, 14 Jul 2020 09:11:06 GMT
E/flutter (13581): #8      runZonedGuarded  (dart:async/zone.dart:1608:12)
E/flutter (13581): #9      _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:233:5)
E/flutter (13581): #10     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (13581): #11     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (13581):`

**Comment by suriyaKalidoss21** [comment]
This contains response only:
`I/flutter (15068): last-modified:Tue, 14 Jul 2020 09:11:06 GMT
I/flutter (15068): date:Tue, 28 Jul 2020 13:01:21 GMT
I/flutter (15068): accept-ranges:bytes
I/flutter (15068): content-length:0
I/flutter (15068): etag:"d41d8cd98f00b204e9800998ecf8427e"
I/flutter (15068): x-amz-request-id:DNBH9RDM3K0Q2XFY
I/flutter (15068): content-type:application/x-directory
I/flutter (15068): x-amz-id-2:/AhbzkwahXlN/9YSYPXUsqAndhi+AoD9h76BAzOA0+RxPkcbwD/7O8ztHkJzxPPSWE4sbgbyi+Y=
I/flutter (15068): server:AmazonS3`

**Comment by knaeckeKami** [comment]
content-lenght is 0, the response body is empty. Weird.

Before the headers, also a HTTP status code should be printed.
What status code does your request give?

**Comment by suriyaKalidoss21** [comment]
200

**Comment by suriyaKalidoss21** [comment]
did you need any other info??

**Comment by suriyaKalidoss21** [comment]
below link is my problem, To secure download the file from s3 I'm using your plugin but your plugin also producing issues, So Please provide a solution to fix the above Xml2Json Exception Issues, 

link: https://stackoverflow.com/questions/63148418/in-agora-cloud-recording-how-to-download-the-file-from-s3-bucket-in-flutter-usin

**Comment by knaeckeKami** [comment]
Ah, I think I found the problem.

I can reproduce this by specifying a wrong bucket id.
What's weird is that AWS just sends a 200 status code with an empty body in this case, but oh well. I should provide a better error message in this case.

In your example code, instead of

```dart
const bucketId = "bucketname/videos";
```

try 

```dart
const bucketId = "bucketname";
```
and then 

```dart
await s3client.listObjects(prefix: 'videos/demo/test', delimiter: '/');
```

**Comment by suriyaKalidoss21** [comment]
I got this error: <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>ba90098ad645d2f70569e3bf9332db53_69.m3u8</Key><RequestId>253BAAA91D60AEA1</RequestId><HostId>w253OAg11ZYEhmQS3uupea7W7PtGMuINuzkl+kgZHJydadvF5/F3ZfvOQkI/Okzb6oUVqy/hl8U=</HostId></Error>

from this code: final response =
      await s3client.getObject("ba90098ad645d2f70569e3bf9332db53_69.m3u8");
  print(response.body.toString());


full response:): getNavigationBarColor() -855310
I/flutter (20350): 200
I/flutter (20350): date:Wed, 29 Jul 2020 10:35:29 GMT
I/flutter (20350): transfer-encoding:chunked
I/flutter (20350): x-amz-request-id:B18BF6F7A7CE96A2
I/flutter (20350): content-type:application/xml
I/flutter (20350): x-amz-id-2:sGsbSH+0CdGvtE1ChU75CDaDPmumkS2MMYKspjMapAuA2Qz1GGeXaMPkji4rKSVnzyFicZacXF0=
I/flutter (20350): server:AmazonS3
I/flutter (20350): x-amz-bucket-region:ap-south-1
I/flutter (20350): Response------><?xml version="1.0" encoding="UTF-8"?>
I/flutter (20350): <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>sct-telemedicine</Name><Prefix>videos/demo/test/</Prefix><KeyCount>7</KeyCount><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><Contents><Key>videos/demo/test/ba90098ad645d2f70569e3bf9332db53_69.m3u8</Key><LastModified>2020-07-28T07:06:27.000Z</LastModified><ETag>&quot;60876ec716deb2115647e743b614a1e6&quot;</ETag><Size>561</Size><StorageClass>STANDARD</StorageClass></Contents><Contents><Key>videos/demo/test/ba90098ad645d2f70569e3bf9332db53_69_20200728070502838.ts</Key><LastModified>2020-07-28T07:05:20.000Z</LastModified><ETag>&quot;1c15d43b9b2639e147422468acbde7b7&quot;</ETag><Size>918568</Size><StorageClass>STANDARD</StorageClass></Contents><Contents><Key>videos/demo/test/ba90098ad645d2f70569e3bf9332db53_69_20200728070518015.ts</Key><LastModified>2020-07-28T07:05:35.000Z</LastModified><ETag>&quot;d6de1f1dd2e7d115a45e68f0571565d2&quot;</ETag><Size>101275
I/flutter (20350): 404
I/flutter (20350): content-type:application/xml
I/flutter (20350): x-amz-request-id:253BAAA91D60AEA1
I/flutter (20350): date:Wed, 29 Jul 2020 10:35:30 GMT
I/flutter (20350): transfer-encoding:chunked
I/flutter (20350): x-amz-id-2:w253OAg11ZYEhmQS3uupea7W7PtGMuINuzkl+kgZHJydadvF5/F3ZfvOQkI/Okzb6oUVqy/hl8U=
I/flutter (20350): server:AmazonS3
I/flutter (20350): Response------><?xml version="1.0" encoding="UTF-8"?>
I/flutter (20350): <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>ba90098ad645d2f70569e3bf9332db53_69.m3u8</Key><RequestId>253BAAA91D60AEA1</RequestId><HostId>w253OAg11ZYEhmQS3uupea7W7PtGMuINuzkl+kgZHJydadvF5/F3ZfvOQkI/Okzb6oUVqy/hl8U=</HostId></Error>
D/InputMethodManager(20350): prepareNavigationBarInfo() DecorView@927c7e5[MainActivity]

**Comment by suriyaKalidoss21** [comment]
My code:

void main() async {

  const region = "ap-south-1";
  const bucketId = "xxx-xxxx";
  final AwsS3Client s3client = AwsS3Client(
      client: DebugClient(Client()),
      region: region,
      host: "s3.ap-south-1.amazonaws.com",
      bucketId: bucketId,
      accessKey: "xxxxxx",
      secretKey: "xxxxx");

  await s3client.listObjects(prefix: 'videos/demo/test/', delimiter: '/');

  final response =
      await s3client.getObject("ba90098ad645d2f70569e3bf9332db53_69.m3u8");
  print(response.body.toString());
}

**Comment by suriyaKalidoss21** [comment]
FYI response.request.URL looks 
like this http://bucketname.s3.ap-south-1.amazonaws.com/videos/demo/test/ba90098ad645d2f70569e3bf9332db53_69.m3u8

**Comment by suriyaKalidoss21** [comment]
FYI 
response.request.url.tostring
 looks like this
https://s3.ap-south-1.amazonaws.com/bucket name/ba90098ad645d2f70569e3bf9332db53_69.m3u8

But my actual file URL in s3 looks like this

http://bucket name.s3.ap-south-1.amazonaws.com/videos/demo/test/ba90098ad645d2f70569e3bf9332db53_69.m3u8

**Comment by knaeckeKami** [comment]
You need to specify the full key in `getObject`, e.g. 

```dart
s3client.getObject('/videos/demo/test/ba90098ad645d2f70569e3bf9332db53_69.m3u8');
```

Or iterate over the contents of the result of `listObjects` and get the keys from there.

**Comment by suriyaKalidoss21** [comment]
Now i got this:
![image](https://user-images.githubusercontent.com/51110790/88792914-a07e2d00-d1b9-11ea-926c-741ae3d571f1.png)

**Comment by suriyaKalidoss21** [comment]
then how to download this file to local??

**Comment by suriyaKalidoss21** [comment]
![image](https://user-images.githubusercontent.com/51110790/88793736-f2738280-d1ba-11ea-8635-3a0eff2185bf.png)
Is there is any running example for this part in flutter?

**Comment by knaeckeKami** [comment]
Looks good, these are the contents of the m3u8 file that are printed. You can remove the line

```dart
client: DebugClient(Client()),
```

so you don't get all this debug lines printed.

In the README of this project there is an example code on how to write the contents into a file. This is meant for very large files to improve performance. For smaller files, you can also do

```dart
    final s3Response = await _awsS3Client.getObject("a");
    await File("your_file_name").writeAsBytes(s3Response.bodyBytes);
```


See

```dart
Future download(String key, File file, [String etag = null]) async {

  final signedParams = s3client.buildSignedGetParams(key: key);

  final request = await HttpClient().getUrl(signedParams.uri);

  for (final header in (signedParams.headers ?? const {}).entries) {
    request.headers.add(header.key, header.value);
  }
  if(eTag != null){
    request.headers.add(HttpHeaders.ifNoneMatchHeader, eTag);
  }
  final response = response = await request.close();
  if(response.statusCode != HttpStatus.ok){
     //handle error  
  }else{
     return response.pipe(file.openWrite());
  }
}
```

**Comment by suriyaKalidoss21** [comment]
Thanks for your help, code working fine, you can close this issue, my feedback is added some more information about this plugin in read me page that will be helpful

**Comment by knaeckeKami** [comment]
Great.
Yes, I should probably add better documentation.
