### ISSUE TITLE
Cancel download

### ISSUE THREAD

**Issue by eplnh** [diagnosia/flutter_aws_s3_client#9]
There is no way to cancel the download in the middle of downloading progress

**Comment by knaeckeKami** [comment]
If you need cancellation, I suggest using the `buildSignedGetParams` method and creating your own HttpClient for that.
Example:

```dart
  
  String key = <your object key>;
  final signedParams = awsS3Client.buildSignedGetParams(key: key);

  final request = await HttpClient().getUrl(signedParams.uri);

  for (final header in (signedParams.headers ?? const {}).entries) {
    request.headers.add(header.key, header.value);
  }

  request.close().then( (response) {
       // use response
  });
 //cancel download
 request.abort(); 
  
```

**Comment by eplnh** [comment]
@knaeckeKami thanks for the suggestion, I'm gonna try it now. Can you tell me, why from the library itself there is no cancel the download progress method or show the download progress method? are there any specific reasons?

**Comment by knaeckeKami** [comment]
mainly because this library was literally the first real dart code that I've written (I needed a simple S3 client for the prototype and nothing else existed at that time) and I kept it simple and based it on the dart `http` package which does not cancellation support currently.
Maybe I'll revamp the package when I have some time.

Btw, here's a snippet to download the response into a file and get progress:

```dart
  /// downloads the http response into the given file. returns a stream with the amount of bytes downloaded
  Stream<int> downloadResponseInto(
      {@required File file,
      @required HttpClientResponse response) {
    assert(file != null);
    assert(response != null);

   
    var currentProgress = 0;
    final controller = StreamController<int>();
    controller.add(currentProgress));
    final observedResponse = response.timeout(const Duration(minutes: 10),
        onTimeout: (sink) {
      sink.addError(
          TimeoutException("timeout when downloadin"), StackTrace.current);
      sink.close();
    }).transform<List<int>>(
        StreamTransformer.fromHandlers(handleData: (data, sink) {
      currentProgress += data.length;
      // yield progress info to the user
      controller.add(  currentProgress));
      //resume stream with unchanged data
      sink.add(data);
    }, handleError: (error, stack, sink) {
      sink.addError(error, stack);
      controller.addError(error, stack);
    }));
    final fileSink = file.openWrite();

    observedResponse
        .pipe(fileSink) //pipe the stream into the file
        .catchError(controller.addError)
        .whenComplete(() async {
      await controller.close();
      await fileSink.flush();
      await fileSink.close();
    }); // closing the controller notifies the subscriber that the download is finished
    return controller.stream;
  }
```

**Comment by eplnh** [comment]
@knaeckeKami I see, thanks for your hard work!

is there any sample how to call this method? Because I don't see the correlation with the s3bucket.

**Comment by knaeckeKami** [comment]
it's not a function of the package. you can copy it into your project. you can get the HttpResponse object like in the snippet that I shared for cancelling download.

**Comment by knaeckeKami** [comment]
Hey,

Since there is now an official package for accessing AWS services, I decided to not longer support this package. please migrate to https://github.com/aws-amplify/amplify-flutter / https://pub.dev/packages/amplify_storage_s3/example
